apiVersion: apps/v1
kind: Deployment
metadata:
  name: kopilot-backend
  labels:
    app: kopilot-backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: kopilot-backend
  template:
    metadata:
      labels:
        app: kopilot-backend
    spec:
      imagePullSecrets:
      - name: ncr-secret
      containers:
      - name: backend
        image: team3-registry.ncr.fin-ntruss.com/kopilot-backend:37e8a67
        ports:
        - containerPort: 8080
        env:
        - name: SPRING_DATASOURCE_URL
          value: "jdbc:mysql://192.168.152.6:3306/kopilot?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=Asia/Seoul&characterEncoding=UTF-8"
        - name: SPRING_DATASOURCE_USERNAME
          value: "kopilot"
        - name: SPRING_DATASOURCE_PASSWORD
          valueFrom:
            secretKeyRef:
              name: backend-secret
              key: mysql-password
        - name: OPENAI_API_KEY
          valueFrom:
            secretKeyRef:
              name: backend-secret
              key: openai-api-key
        - name: SPRING_DATA_REDIS_HOST
          value: "cache-48sg4s-fkr.cdb.fin-ntruss.com"
        - name: SPRING_DATA_REDIS_PORT
          value: "6379"
        resources:
          requests:
            cpu: "500m"
            memory: "1Gi"
          limits:
            cpu: "500m"
            memory: "1Gi"