apiVersion: apps/v1
kind: Deployment
metadata:
  name: kopilot-frontend
  labels:
    app: kopilot-frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: kopilot-frontend
  template:
    metadata:
      labels:
        app: kopilot-frontend
    spec:
      imagePullSecrets:
      - name: ncr-secret
      containers:
      - name: frontend
        image: team3-registry.ncr.fin-ntruss.com/kopilot-frontend:b92c8bf
        ports:
        - containerPort: 80
        resources:
          requests:
            cpu: "500m"
            memory: "1Gi"
          limits:
            cpu: "500m"
            memory: "1Gi"
