name: CI Frontend

on:
  push:
    branches: [ "prod" ]
    paths:
      - 'check-kopilot/frontend/**'
  pull_request:
    branches: [ "prod" ]
    paths:
      - 'check-kopilot/frontend/**'

jobs:
  build:
    runs-on: self-hosted
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      
    - name: Set up Node.js 20
      uses: actions/setup-node@v4
      with:
        node-version: '20'
        cache: 'npm'
        cache-dependency-path: './check-kopilot/frontend/package-lock.json'
        
    - name: Install dependencies
      working-directory: ./check-kopilot/frontend
      run: npm ci
      
    - name: Build Frontend (React Vite)
      working-directory: ./check-kopilot/frontend
      run: npm run build
